# config file

# path to pipeline repo
path_to_repo: "/projects/p31346/suggie/hxrate_pipeline"


# PO_filtered_data

# You can use the auxiliar script to generate the consolidated_results.json file from the individual consolidated_results.json files
# in each of the pH folders. The script is located in the pipeline repo: {path-to-repo}/hxrate_pipeline/auxiliar/concatenate_dataframes.py

# If you just have one pH condition, you can use the single pH consolidated_results.json file in
# {path-to-hdxlim results}/resources/10_ic_time_series/consolidated_results.json as the path_to_filtered_data value

path_to_filtered_data: "/scratch/ajf4103/HX_pipeline/mutants/mutants_4/consolidated_results.json"

library: "mutants04" # this name should correspond to the library value in the consolidated_results.json file

single_pH : False # if you have only one pH condition, set this to True
###############################################

# output directory path
output_dirpath: "rate_fit_output"

# low ph info
low_ph_library_info: "/projects/b1107/allan/HDX_analysis/Lib15/20211225_pH6/hdx_limit-pipeline/resources/7_idotp_filter/checked_library_info.json"
lowph_protein_rt_column_name: "name_rt-group"

low_ph_hxms_fpath_delim_str: "_winner_multibody.cpickle.zlib.csv"
low_ph_hxms_fpath_dir: "/projects/b1107/allan/HDX_analysis/Lib15/20211225_pH6/hdx_limit-pipeline/resources/10_ic_time_series"
level_to_fpaths_low_ph: 1
lowph_hdxlim_dirstruct: True
low_hdxlim_pathtype_str: "multibody"

low_ph_exp_label: "pH6" # don't change this but confirm that this matches the label in pH column of the consolidated_results.json file
low_ph_d2o_frac: 0.90
low_ph_d2o_pur: 0.95

## optional
#low_ph_backexchange_correction_fpath:


# high ph info
high_ph_library_info: "/projects/b1107/allan/HDX_analysis/Lib15/20211223_pH9/hdx_limit-pipeline/resources/7_idotp_filter/checked_library_info.json"
highph_protein_rt_column_name: "name_rt-group"

high_ph_hxms_fpath_delim_str: "_winner_multibody.cpickle.zlib.csv"
high_ph_hxms_fpath_dir: "/projects/b1107/allan/HDX_analysis/Lib15/20211223_pH9/hdx_limit-pipeline/resources/10_ic_time_series"
level_to_fpaths_high_ph: 1
highph_hdxlim_dirstruct: True
high_hdxlim_pathtype_str: "multibody"

high_ph_exp_label: "pH9" # don't change this but confirm that this matches the label in pH column of the consolidated_results.json file

high_ph_d2o_frac: 0.90
high_ph_d2o_pur: 0.95

##optional
#high_ph_backexchange_correction_fpath:


# merge rt window search
merge_rt_window: 1.0

# saturate mass rate threshold to check if the path has reached maximum deuteration
saturation_mass_rate: 0.03


# backexchange bounds for correlation
backexhange_low_bound: 0.15
backexchange_up_bound: 0.45





##########################################
##########################################
#backexchange correction parameters

# backexchange correction bool
backexchange_correction: True
rate_tol: 0.06
min_num_points: 5
change_rate_threshold: 0.02

##########################################
##########################################

# rate fitting parameters
adjust_backexchange: True
sample_backexchange: False
num_chains: 4
num_warmups: 100
num_samples: 250
num_cores: 6

dg_calc: True
# dg fitting parameters
low_pH: 6.0
high_pH: 9.0
min_fe: -2.0
temp: 295
net_charge_corr: True


