# config file

# do not put a backslash after the directory

# path to the repo
path_to_repo: "/projects/p31346/suggie/hxrate"

# params to find the hx ms distribution fpaths
hx_ms_dist_fpaths_top_dir: "/projects/p31346/suggie/hdx_ms_analysis"
levels_to_fpaths: 2
hx_ms_fpath_delim_string: "_winner.cpickle.zlib.csv"

# pdb fpaths
pdb_fpaths_dir: "/projejcts/p31346/suggie/pdbs"

# library info filepath
library_info_json_fpath: "/projects/p31346/suggie/hx_rates_workfolder/library_info.json"

# output directory where all the outputs will be placed
output_dirpath: "/projects/p31346/suggie/hx_rates_workfolder/output"

##########################################
##########################################
#backexchange correction parameters

# backexchange correction bool
backexchange_correction: True
rate_tol: 0.15
min_num_points: 5
change_rate_threshold: 0.02

# give the backexchange correction filepath if it already exists.
# If not provided, the workflow will create it automatically if backexchange correction is turned on
backexchange_correction_fpath:

##########################################
##########################################


# exp params
d2o_fraction: 0.95
d2o_purity: 0.95


# rate fitting parameters
adjust_backexchange: True
sample_backexchange: False
num_chains: 4
num_warmups: 100
num_samples: 500


dg_calc: False
# dg fitting parameters
pH: 6.15
temp: 295
nterm: ''
cterm:  ''
net_charge_corr: True
anneal_time: 2.0
anneal_update_interval: 100

