# config file

# path to the repo
path_to_repo: "/projects/p31346/suggie/hxrate"

###############################################

# low ph info
low_ph_library_info: ""
low_ph_hxms_fpath_delim_str: "_winner.cpickle.zlib.csv"
low_ph_hxms_fpath_dir: ""
level_to_fpaths_low_ph: 1

low_ph_d2o_frac: 0.95
low_ph_d2o_pur: 0.95

low_ph_backexchange_correction_fpath:


# high ph info
high_ph_library_info: ""
high_ph_hxms_fpath_delim_str: "_winner.cpickle.zlib.csv"
high_ph_hxms_fpath_dir: ""
level_to_fpaths_high_ph: 1

high_ph_d2o_frac: 0.95
high_ph_d2o_pur: 0.95

high_ph_backexchange_correction_fpath:


# merge rt window search
merge_rt_window: 1.0

# saturate mass rate threshold to check if the path has reached maximum deuteration
saturation_mass_rate: 0.03


# backexchange bounds for correlation
backexhange_low_bound: 0.15
backexchange_up_bound: 0.30



# output directory path
output_dirpath: "/projects/p31346/suggie/hx_rates_workfolder/merge_output"



##########################################
##########################################
#backexchange correction parameters

# backexchange correction bool
backexchange_correction: True
rate_tol: 0.05
min_num_points: 1
change_rate_threshold: 0.02

##########################################
##########################################

# rate fitting parameters
adjust_backexchange: True
num_chains: 4
num_warmups: 100
num_samples: 500
