# config file

# path to the repo
path_to_repo: "/projects/p31346/suggie/hxrate"

# params to find the hx ms distribution fpaths
hx_ms_fpath_delim_string: ".winner.cpickle.zlib.csv"
hx_ms_dist_fpaths_top_dir: "/projects/p31346/suggie/hdx_ms_analysis"
level_to_fpaths: '/*/*'

# library info filepath
library_info_json_fpath: "/projects/p31346/suggie/hx_rates_workfolder/library_info.json"

# hxrate fitting params filepath
param_fpath: "/projects/p31346/suggie/hxrate/params/params.yml"

# output directory where all the outputs will be placed
output_dirpath: "/projects/p31346/suggie/hx_rates_workfolder/lib15_ph8_output"

# backexchange correction bool
backexchange_correction: True

# give the backexchange correction filepath. If not provided, the workflow will create it automatically
backexchange_correction_fpath:

# exp params
d2o_fraction: 0.95
d2o_purity: 0.95

# user can set their own backexchange
usr_backexchange:

# rate fitting parameters
opt_iter: 50
opt_temp: 0.0003
opt_step_size: 0.02

# rate fitting multiprocessing utility
multi_proc: True
number_of_cores: 6
